Fix new element insertion failures on PostgreSQL 12
Was getting this:

select Element_Add('/ports/head/www/httpdirfs/', 'F');

ERROR:  duplicate key value violates unique constraint "element_pathname_pathname" DETAIL:  Key (pathname)=() already exists.


Because:

      INSERT INTO element_pathname (element_id, pathname)
         VALUES (NEW.id, element_pathname(NEW.id));

The pathname value was always NULL.

The fix, change the SQL to:

   DECLARE
     l_pathname  text;
   BEGIN
     l_pathname := element_pathname(NEW.id);
     INSERT INTO element_pathname (element_id, pathname) 
         VALUES (NEW.id, l_pathname);






git-svn-id: svn://127.0.0.16/freshports-1/database-schema@5233 46e82423-29d8-e211-989e-002590a4cdd4